### ISSUE TITLE
Docker image on dockerhub is out of date

### ISSUE THREAD

**Issue by artdgn** [mps-youtube/yewtube#1049]
Not sure if this repo is still maintained, but anyway:

Pulling and running the docker image results in the old version (from 2016), which doesn't work.

Version:
```
docker run --device /dev/snd -it --rm --name mpsyt rothgar/mpsyt --version
WARNING:root:pafy: youtube-dl not found; falling back to internal backend. This is not as well maintained as the youtube-dl backend. To hide this message, set the environmental variable PAFY_BACKEND to "internal".
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (internal backend)
Python version     : 3.6.0 (default, Feb 10 2017, 02:01:06) 
[GCC 4.9.2]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.15.0-72-generic-x86_64-with-debian-8.7
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /root/.config/mps-youtube
env:TERM           : xterm
env:LANG           : C.UTF-8
```

## Issue / Suggestion
It's possible now to allow [auto-builds on dockerhub](https://docs.docker.com/docker-hub/builds/) (integration with github) so that images are up to date automatically.

**Comment by tommysolsen** [comment]
Yeah, im uncertain who actually maintains(or maintained) the docker image. It has not been updated for as long as I've been here. 

I've submitted a PR(#1050) for some changes regarding the Docker images. There is a docker image that has been built from the current development source at `mpsyt/mps_youtube:develop`.

It might take some time before this issue is fully resolved so hopefully this can help you in the mean time

**Comment by artdgn** [comment]
Thanks! Did you have a look at the auto-builds link? Not sure, but It might be a simpler setup than github actions. (I have the auto-builds set up for some of my personal repos and it was literately a few clicks, + it also syncs the README.md to the dockerhub page)

**Comment by tommysolsen** [comment]
Yeah, the auto build functionality is pretty sweet. I didn't have access to set it up for the org against this repo, but it looks like a good way to build the images.

There was mostly two reasons why I decided against dokcerhub auto-build. Though I have only skimmed the documentation slightly.

The first is that in the future, I would like to see us able to publish new versions to more platforms than docker automatically. Make it so we can just tag a version on github and deploy to all of the channels we distribute mpsyt, such as the apt repositories for debian and ubuntu, AUR for Arch Linux, PIP and the purpose built windows binaries that are generated. Most of these would require a tool like Actions, so keeping them all in one spot was nice. (Using actions actually also gives me a windows machine to test building the executables, as I dont have a windows pc myself anymore).

The second being that it is somewhat valuable for us to be able to rebuild some of these images with no change to the code. A lot of the errors I get, and seemingly others as well are because youtube-dl is out of date. Down the line, I'dd love to automate the process of rebuilding selected images(latest, develop, etc) whenever youtube dl is updated. This would be possible using actions by having a scheduled job run a check to see if the version has changed and then triggering a deployment event through github rest api.

**Comment by artdgn** [comment]
Thanks for the detailed explanation, that makes perfect sense :+1:

**Comment by pataquets** [comment]
+1 for updating the Docker image.
@artdgn As a workaround, `docker build` command supports a git repo URL as parameter 😉 (see docs)

**Comment by iamtalhaasghar** [comment]
If anyone is interested in maintaining docker image of `yewtube` then you can create a new PR and we can coordinate on this. Also see https://github.com/mps-youtube/yewtube/pull/1050
