### ISSUE TITLE
Incomplete search results

### ISSUE THREAD

**Issue by StylinGreymon** [mps-youtube/yewtube#1064]
Looking over a recent search, I realized that there were quite a few videos missing from the results, most notably a 1-month gap between January and February.
![image](https://user-images.githubusercontent.com/5328232/75424931-7ec10700-58f6-11ea-966f-f63086ab76d3.png)

Not sure when this started happening, and the full list of videos shows up regularly in a web browser.

## Your Environment
>mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2020.02.16
Python version     : 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.4.18-1-MANJARO-x86_64-with-glibc2.2.5
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/greymon/.config/mps-youtube
env:TERM           : screen-256color
env:SHELL          : /bin/zsh
env:LANG           : en_US.UTF-8

EDIT: I can't reproduce this error on any other search besides game grumps, but for some reason both 'user gamegrumps' and 'channels gamegrumps' return incomplete results, though the exact result differs.

**Comment by UpHillSolutions-roberth** [comment]
I just recently started using yewtube so apologies for being so late however this issue is also happening for me. 

It looks like you are doing a `channels` or `user` search. 

I'm seeing this issue in both of those search query types as well. 

I have solved the issue on my end and submitted a pull request for the fix: https://github.com/mps-youtube/yewtube/pull/1282

I hope this helps!
