### ISSUE TITLE
ERROR: No video formats found...

### ISSUE THREAD

**Issue by yohannes** [mps-youtube/yewtube#1100]
## Issue / Suggestion

After showing a search result, I always received the following error message: 

```
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Even though youtube-dl was only recommended in the doc to be installed for linux, i went ahead and installed it too. No dice. i still received the above message afterwards. I also tried to set the `video_format` variable in the config to `mp4` from `auto` but ddin't work either. Searched for the error message online but results were specific to youtube-dl not mpyst. Any pointer on what do you recommend me do? Thanks

## Your Environment

mpyst was installed via homebrew along w/ all the relevant dependencies

mpyst 0.2.8

MacOS Catalina 10.15.5

n/a

**Comment by Grubben** [comment]
The same is happening to me.
When I try searching for example "hello" I get this: https://pastebin.com/ABcYgMuE
When I go ahead and choose the first option despite the error I get this: https://pastebin.com/SbbYRQ0y repeating the "During handling of[...]"
I am on a Mac with MacOS Mojave; Version 10.14.6 (18G5033)
Any other information needed I will provide

**Comment by macgeekpro** [comment]
Just to add to @Grubben 's two logs that are identical to mine, the mps-youtube instance also crashed at the end of the 2nd log output.

**Comment by ikuraj** [comment]
Same issue here.

**Comment by pir4cy** [comment]
Same issue

**Comment by eph-oph** [comment]
Exact same issue as OP
I've tired multiple reinstalls with both brew and pip3 to no avail.
I've noticed with latest YouTube-dl I have to manually add quotes " " to the video URL the since updating. I'm wondering if quotes need to be passed along now?

**Comment by repodevs** [comment]
Any update for this? I'm have same issue too

**Comment by giondo** [comment]
same issue here, do you need some logs ?

**Comment by CaesarOG** [comment]
Wow, I've seen people experience this issue across the last three years on different operating systems. Genius. Note to all just stop using this, it's extremely unreliable. Just use Tizonia - it actually works and goes beyond just Youtube - also has Google-Play Music and Spotify. Instead of waiting around and begging them to do something they haven't been able to consistently fix for three years, take a word to the wise and jump ship.

**Comment by CaesarOG** [comment]
Wow, I've seen people experience this issue across the last three years on different operating systems. Genius. Note to all just stop using this, it's extremely unreliable. Just use Tizonia - it actually works and goes well beyond just Youtube, also providing Google-Play Music and Spotify. Instead of waiting around and begging them to do something they haven't been able to consistently fix for three years, take a word to the wise and jump ship.

**Comment by jagamypriera** [comment]
@CaesarOG is it available on mac?

**Comment by iamtalhaasghar** [comment]
see #1191
