### ISSUE TITLE
Make use of internal Youtube playlists

### ISSUE THREAD

**Issue by ghost** [mps-youtube/yewtube#12]
Many Youtube users have pre-compiled playlists, so there's sometimes no need to build one yourself. Being able to search for and utilize playlists straight from youtube would be a great feature.

**Comment by Jarshvor** [comment]
hi, im sorry if this is the wrong place to ask about this, or if its been brought up before, but I cant get mpsyt to display all items on a large youtube-playlist. (https://www.youtube.com/playlist?list=PLF6F3B71FFD2611B5)

ive tried the dump command but it only makes it to the 200th item, (184 on the list since some vids have been deleted).

is there something im missing?
