### ISSUE TITLE
time for new release?

### ISSUE THREAD

**Issue by pirate486743186** [mps-youtube/yewtube#955]
The last release came out a year ago. Maybe it's time for a new release?

**Comment by diego-treitos** [comment]
I am also wondering if it is time for a new release, now that `0.2.8` is broken for the new `mpv` version and it is already fixed in git.

People can go back to a previous version of `mps-youtube` if they want but we cannot install a release that does not exist.

I am wondering why no new releases are being published in such a long time... but I hope this changes soon because if not I will have to look for an alternative and I very much love `mps-youtube`.

Please, launch a new release.

**Comment by debdrup** [comment]
Yes, a new release would be lovely. 
[Systems such as FreeBSD Ports](https://www.freshports.org/multimedia/mps-youtube) generally work on tested releases, rather than simply grabbing the latest available release - so not doing new releases makes this much harder.

**Comment by iamtalhaasghar** [comment]
`pip install yewtube`
